name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .env
        run: |
          touch .env
          echo FAKE_VAR_WITH_ESCAPE=\"${{ vars.FAKE_VAR }}\" >> .env
          echo FAKE_VAR="${{ vars.FAKE_VAR }}" >> .env
          echo FAKE_VAR_QUOTED="${{ vars.FAKE_VAR_QUOTED }}" >> .env
      - name: Check .env
        run: cat .env
