name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .env
        run: |
          touch .env
          echo FAKE_SECRET_WITH_ESCAPE=\"${{ secrets.FAKE_SECRET }}\" >> .env
          echo FAKE_SECRET="${{ secrets.FAKE_SECRET }}" >> .env
          echo FAKE_SECRET_QUOTED="${{ secrets.FAKE_SECRET_QUOTED }}" >> .env
      - name: Check .env
        run: cat .env
